version: '3'
services:

  #Nginx Service
  crypto_webserver:
    image: nginx:alpine
    container_name: crypto_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "4321:80"
      - "243:443"
    volumes:
      - ./:/var/www
      - ./compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - crypto-network

  #PHP Service
  crypto_app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: crypto_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - crypto-network

  #MySQL Service
  crypto_db:
    image: mariadb:10.5.8
    container_name: crypto_db
    restart: unless-stopped
    tty: true
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql/
      - ./compose/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - crypto-network



#Docker Networks
networks:
  crypto-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
